name: Checkout Repository

on: push
jobs:
  checkout-repository:
    runs-on: ubuntu-20.04
    steps:
      # Checkout Repository, now lives in $GITHUB_REPOSITORY
      - name: Checkout repository
        uses: actions/checkout@v2
      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2
        # Specify some input for this particular action
        with:
          python-version: '3.8.6'
      # Install PyTest and Flask
      - name: Install Dependencies
        run: pip install -r requirements.txt
      # Run the tests
      - name: Run tests
        run: pytest
      #Start deployment

#Now lives in $GITHUB_REPOSITORY
#https://github.com/marketplace/actions/checkout