name: Checkout Repository

on: push
jobs:
  checkout-repository:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

#Now lives in $GITHUB_REPOSITORY
#https://github.com/marketplace/actions/checkout